from enum import Enum

class ReclaimStatus(str, Enum):
    READY = "READY"
    IN_PROGRESS = "IN-PROGRESS"
    DONE = "DONE"

class DetailStatus(str, Enum):
    READY = "READY"
    IN_PROGRESS = "IN-PROGRESS"
    REJECTED = "REJECTED"
    DHCP_REQUESTED = "DHCP_REQUESTED"
    DHCP_SUCCESS = "DHCP_SUCCESS"
    DHCP_FAILED = "DHCP_FAILED"
    DEVICE_REQUESTED = "DEVICE_REQUESTED"
    DEVICE_SUCCESS = "DEVICE_SUCCESS"
    DEVICE_FAILED = "DEVICE_FAILED"
